### ISSUE TITLE
Translate to another Language .

### ISSUE THREAD

**Issue by ithouse98** [abhishtagatya/piWeatherman#2]
Hi guys , thanks to your use full develop.
i need to translate this to my Native language ,
may every body can provide me a guide or help in this reason .
thanks

**Comment by abhishtagatya** [comment]
Hi @ithouse98 that's a great idea, a simple way to do it is to create a language file or maybe just simple json and map it on based on the requested language. Thanks for the feedback and contribution.

**Comment by ithouse98** [comment]
thanks , may you help me in this way 🙏☺️

**Comment by abhishtagatya** [comment]
@ithouse98 unfortunately, i have no interest developing this project currently, maybe in the future. But you could contribute it yourself.

**Comment by ithouse98** [comment]
😔😐 ok . thanks to you.
